config-version = 2

start-at-login = true

# Containers with a single child are destroyed and the child takes its place.
enable-normalization-flatten-containers = true
# Nested containers have the opposite orientation.
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
# With 'auto', wide monitors will default to vertical, and high monitors will
# default to horizontal.
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'main'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

# All possible keys for keybindings:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote,
#                   semicolon, backtick, leftSquareBracket, rightSquareBracket,
#                   space, enter, esc, backspace, tab, pageUp, pageDown, home,
#                   end, forwardDelete, sectionSign (ISO keyboards only,
#                   european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter,
#                   keypadEqual, keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
#
# All possible modifiers for keybindings: cmd, alt, ctrl, shift
#
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-shift-slash = 'layout accordion horizontal vertical'

alt-f = 'layout floating tiling'
alt-shift-f = 'fullscreen'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-0 = 'balance-sizes'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
keypad1 = 'workspace 1'
keypad2 = 'workspace 2'
keypad3 = 'workspace 3'
keypad4 = 'workspace 4'
keypad5 = 'workspace 5'
keypad6 = 'workspace 6'
keypad7 = 'workspace 7'
keypad8 = 'workspace 8'
keypad9 = 'workspace 9'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
shift-keypad1 = ['move-node-to-workspace 1', 'workspace 1']
shift-keypad2 = ['move-node-to-workspace 2', 'workspace 2']
shift-keypad3 = ['move-node-to-workspace 3', 'workspace 3']
shift-keypad4 = ['move-node-to-workspace 4', 'workspace 4']
shift-keypad5 = ['move-node-to-workspace 5', 'workspace 5']
shift-keypad6 = ['move-node-to-workspace 6', 'workspace 6']
shift-keypad7 = ['move-node-to-workspace 7', 'workspace 7']
shift-keypad8 = ['move-node-to-workspace 8', 'workspace 8']
shift-keypad9 = ['move-node-to-workspace 9', 'workspace 9']

alt-t = 'exec-and-forget wezterm cli spawn --new-window'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
